In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import pandas_datareader.data as web
import time
import tensorflow
import matplotlib.pyplot as plt
import datetime as dt
import numpy as np
import logging
import math
import os
from sklearn.preprocessing import MinMaxScaler, scale
from keras.utils import np_utils
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Activation
from keras import optimizers
from sklearn.metrics import mean_squared_error
from keras.models import load_model
from tqdm import tqdm_notebook
from sklearn.model_selection import train_test_split

Using TensorFlow backend.

In [2]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.max_rows', 500)

# 데이터 불러오기 / 데이터 정리

In [3]:
IT_nonfinance = pd.read_excel('./data/dongboo/비재무/IT_비재무_TOTAL_최종.xlsx')
IT_validation_nonfinance = pd.read_excel('./data/dongboo/비재무validation/validation_비재무_it_total_최종.xlsx')

In [4]:
# 
IT_stock = pd.read_excel('./data/dongboo/IT_주가_total_krx.xlsx')

IT_validation_stock = pd.read_excel('./data/dongboo/IT_validation_주가.xls')

In [5]:
IT = pd.merge(IT_nonfinance,IT_stock,how = 'left', on = ['회사명','거래소코드','회계년도'])

IT_val = pd.merge(IT_validation_nonfinance,IT_validation_stock,how = 'left', on = ['회사명','거래소코드','회계년도'])

In [6]:
#del IT['주식매입선택권.1']

# 회사별로 분리

In [7]:
lg = IT[IT['회사명'] == 'LG이노텍(주)']
sdi = IT[IT['회사명'] == '삼성SDI(주)']
ssem = IT[IT['회사명'] == '삼성전기(주)']
hynix = IT[IT['회사명'] == '에스케이하이닉스(주)']

# ------------- validation ------------------

samsungelectric = IT_val[IT_val['회사명'] == '삼성전자(주)']
lgelectric = IT_val[IT_val['회사명'] == '엘지전자(주)']
sds = IT_val[IT_val['회사명'] == '삼성에스디에스(주)']
lgdisplay = IT_val[IT_val['회사명'] == '엘지디스플레이(주)']

In [8]:
def classify(stock):
    
    # 회계년도 순으로 정렬 및 인덱스 초기화
    stock.sort_values('회계년도', ascending= True, inplace = True)
    
    stock.reset_index(drop = True, inplace = True)
    
    
    # 새로운 변수 추가
    
    stock['3개월후종가'] = stock['종가'][1:].reset_index(drop=True)
    
    stock['분기수익률'] = (stock['3개월후종가'] - stock['종가']) / stock['종가']
    
    stock['수익률상승하락'] = stock['분기수익률']
    
    for i in range(len(stock)):
        if stock['분기수익률'][i] < 0.005:
            stock['수익률상승하락'][i] = 0
        else:
            stock['수익률상승하락'][i] = 1
        
       
    return stock

In [9]:
classify(lg)
classify(sdi)
classify(ssem)
classify(hynix)

# ------------- validation ------------------

classify(samsungelectric)
classify(lgelectric)
classify(sds)
classify(lgdisplay)

           회사명  거래소코드     회계년도  주식의 종류  발행할 주식의 총수(주)  현재까지 발행한 주식의 총수(주)  현재까지 감소한 주식의 총수(주)  유통주식수 (발행주식의 총수 - 자기주식수)(주)  이익소각(주)  발행주식의 총수 (현재 발행한 주식수 - 현재 감소한 주식수)(주)  자기주식수(주)  정규+무기계약_기말인원(남)(명)  정규+무기계약_기말인원(여)(명)  정규+무기계약_기말인원(명)  기간제_기말인원(남)(명)  기간제_기말인원(여)(명)  기간제_기말인원(명)  합계_기말인원_남(명)  합계_기말인원_여(명)  합계_기말인원(명)  합계_년간평균급여(천원)  합계_1인평균년간급여(천원)  합계_평균근속연수    최고가    최저가     종가       거래량           거래대금   3개월후종가     분기수익률  수익률상승하락
0   엘지디스플레이(주)  34220  2010/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               20995                9122            30117               0               0            0         20995          9122       30117     1282387000            42000        4.3  41700  38900  40300  50464767  2033069299170  35075.0 -0.129653      0.0
1   엘지디스플레이(주)  34220  2011/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               22503                9818            32321               0               0            0         22503          9818       32321      516829000            16000        4.1  36500  33650  35075  59481024  2079282228250  31625.0 -0.098361      0.0
2   엘지디스플레이(주)  34220  2011/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               23982               10136            34118               0               0            0         23982         10136       34118      869415000            27000        4.1  35200  28050  31625  75248275  2336593713600  19525.0 -0.382609      0.0
3   엘지디스플레이(주)  34220  2011/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               24130               10512            34642               0               0            0         24130         10512       34642     1214680000            37000        4.3  21550  17500  19525  65141512  1275308524800  24275.0  0.243278      1.0
4   엘지디스플레이(주)  34220  2011/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               24195               10608            34803               0               0            0         24195         10608       34803     1562234000            47000        4.5  26300  22250  24275  54301825  1309194344350  28000.0  0.153450      1.0
5   엘지디스플레이(주)  34220  2012/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               24217               10596            34813               0               0            0         24217         10596       34813      438722000            13000        4.2  29650  26350  28000  56698931  1593347436250  21575.0 -0.229464      0.0
6   엘지디스플레이(주)  34220  2012/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               24229               10603            34832               0               0            0         24229         10603       34832      801731000            23000        4.4  23100  20050  21575  44686364   977616803750  27725.0  0.285052      1.0
7   엘지디스플레이(주)  34220  2012/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               23969               10665            34634               0               0            0         23969         10665       34634     1173078000            34000        4.6  29400  26050  27725  45288195  1262835728640  32550.0  0.174031      1.0
8   엘지디스플레이(주)  34220  2012/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               23978               10679            34657               0               0            0         23978         10679       34657     1653773000            47000        4.7  35400  29700  32550  48483018  1560545926825  31475.0 -0.033026      0.0
9   엘지디스플레이(주)  34220  2013/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               24278               10436            34714               0               0            0         24278         10436       34714      478460000            14000        4.9  33050  29900  31475  40348389  1281195813400  28950.0 -0.080222      0.0
10  엘지디스플레이(주)  34220  2013/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               24132               10118            34250               0               0            0         24132         10118       34250      868296000            25000        5.2  31950  25950  28950  42220903  1238200978650  27675.0 -0.044041      0.0
11  엘지디스플레이(주)  34220  2013/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               24208               10029            34237               0               0            0         24208         10029       34237     1258983000            36000        5.4  29400  25950  27675  49782482  1374042444300  24325.0 -0.121048      0.0
12  엘지디스플레이(주)  34220  2013/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               23760                9883            33643               0               0            0         23760          9883       33643     1767922000            51000        6.0  25350  23300  24325  29844567   735171629300  24875.0  0.022610      1.0
13  엘지디스플레이(주)  34220  2014/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               23681                9524            33205               0               0            0         23681          9524       33205      531473000            16000        6.0  26650  23100  24875  36009470   906128484000  29300.0  0.177889      1.0
14  엘지디스플레이(주)  34220  2014/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               23500                9316            32816               0               0            0         23500          9316       32816      934351000            28000        6.2  31800  26800  29300  32676138   968279952700  34600.0  0.180887      1.0
15  엘지디스플레이(주)  34220  2014/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               23416                9176            32592               0               0            0         23416          9176       32592     1412826000            43058        6.4  35700  33500  34600  21944084   761272894975  34750.0  0.004335      0.0
16  엘지디스플레이(주)  34220  2014/12      10      460000000           357815700                   0                    357815700        0                              357815700         0               23356                9078            32434               0               0            0         23356          9078       32434     1828891000            56000        6.6  35850  33650  34750  18700338   642591892100  32075.0 -0.076978      0.0
17  엘지디스플레이(주)  34220  2015/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               23489                8883            32372               0               0            0         23489          8883       32372      798189000            25000        6.8  33500  30650  32075  40030093  1279932379200  27450.0 -0.144193      0.0
18  엘지디스플레이(주)  34220  2015/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               23599                8791            32390               0               0            0         23599          8791       32390     1218162000            38000        7.1  29900  25000  27450  38183591  1037010489442  23975.0 -0.126594      0.0
19  엘지디스플레이(주)  34220  2015/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               23763                8930            32693               0               0            0         23763          8930       32693     1709319000            53000        7.2  25400  22550  23975  36455157   876405608809  24900.0  0.038582      1.0
20  엘지디스플레이(주)  34220  2015/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               23683                8843            32526              28              49           77         23711          8892       32603     2155800000            66000        7.4  25900  23900  24900  37856499   946514528600  25375.0  0.019076      1.0
21  엘지디스플레이(주)  34220  2016/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               23781                8717            32498              28              48           76         23809          8765       32574      818742000            25000        7.6  26950  23800  25375  36095567   911933780328  25000.0 -0.014778      0.0
22  엘지디스플레이(주)  34220  2016/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               23647                8586            32233              35              62           97         23682          8648       32330     1245808000            39000        7.9  26400  23600  25000  24882384   616167980650  29375.0  0.175000      1.0
23  엘지디스플레이(주)  34220  2016/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               23703                8515            32218               0              73          112         23742          8588       32330     1733552000            53000        8.1  30850  27900  29375  21392299   623290960550  29900.0  0.017872      1.0
24  엘지디스플레이(주)  34220  2016/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               23557                8453            32010              40              68          108         23597          8521       32118     2157793000            67000        8.2  32000  27800  29900  25814640   788025839800  29075.0 -0.027592      0.0
25  엘지디스플레이(주)  34220  2017/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               23832                8359            32191              77              78          155         23909          8437       32346      803111000            25000        8.4  30450  27700  29075  40009339  1155153860876  35375.0  0.216681      1.0
26  엘지디스플레이(주)  34220  2017/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               24327                8211            32538              52              65          117         24379          8276       32655     1251138000            39000        8.6  38150  32600  35375  78225463  2840366824550  32125.0 -0.091873      0.0
27  엘지디스플레이(주)  34220  2017/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               24899                8228            33127               0              60          115         24954          8288       33242     1768873000            54000        8.7  34000  30250  32125  77913482  2499250976385  30025.0 -0.065370      0.0
28  엘지디스플레이(주)  34220  2017/12      10      500000000           357815700                   0                    357815700        0                              357815700         0               25054                8168            33222              55              58          113         25109          8226       33335     2258456000            69000        8.7  30650  29400  30025  50458063  1514729322627  27475.0 -0.084929      0.0
29  엘지디스플레이(주)  34220  2018/03      10      500000000           357815700                   0                    357815700        0                              357815700         0               25308                8097            33405              65              55          120         25373          8152       33525     1003075000            30000        8.9  29250  25700  27475  48387169  1326224062603  20300.0 -0.261146      0.0
30  엘지디스플레이(주)  34220  2018/06      10      500000000           357815700                   0                    357815700        0                              357815700         0               25448                7986            33434              55              33           88         25503          8019       33522     1467271000            45000        9.2  23100  17500  20300  54487875  1098139186564  20500.0  0.009852      1.0
31  엘지디스플레이(주)  34220  2018/09      10      500000000           357815700                   0                    357815700        0                              357815700         0               25000                7933            32933               0              27           74         25047          7960       33007     1992389000            61000        9.4  22050  18950  20500  36995734   747917267000      NaN       NaN      1.0

In [10]:
lg = lg.iloc[:-1,:]
sdi = sdi.iloc[:-1,:]
ssem = ssem.iloc[:-1,:]
hynix = hynix.iloc[:-1,:]

# ------------- validation ------------------

samsungelectric = samsungelectric.iloc[:-1,:]
lgelectric = lgelectric.iloc[:-1,:]
sds = sds.iloc[:-1,:]
lgdisplay = lgdisplay.iloc[:-1,:]

# 산업별 변수 <3개월 후 종가>와의 상관관계 분석

In [11]:
# 밑에 함수로 해보기!!!!

In [12]:
lg_corr = lg.corr(method = 'pearson')
df_lg = pd.DataFrame(lg_corr['3개월후종가']).reset_index().sort_values('3개월후종가', ascending = False)
df_lg.columns = ['지표','3개월후종가']

sdi_corr = sdi.corr(method = 'pearson')
df_sdi = pd.DataFrame(sdi_corr['3개월후종가']).reset_index().sort_values('3개월후종가', ascending = False)
df_sdi.columns = ['지표','3개월후종가']

ssem_corr = ssem.corr(method = 'pearson')
df_ssem = pd.DataFrame(ssem_corr['3개월후종가']).reset_index().sort_values('3개월후종가', ascending = False)
df_ssem.columns = ['지표','3개월후종가']

hynix_corr = hynix.corr(method = 'pearson')
df_hynix = pd.DataFrame(hynix_corr['3개월후종가']).reset_index().sort_values('3개월후종가', ascending = False)
df_hynix.columns = ['지표','3개월후종가']

# 산업별 상관관계 데이터프레임

In [13]:
pd.concat([df_lg.reset_index(drop = True), df_sdi.reset_index(drop = True), df_ssem.reset_index(drop = True), df_hynix.reset_index(drop = True)],axis = 1)

                                       지표    3개월후종가                                     지표    3개월후종가                                     지표    3개월후종가                                     지표    3개월후종가
0                                  3개월후종가  1.000000                                 3개월후종가  1.000000                                 3개월후종가  1.000000                                 3개월후종가  1.000000
1                                     최고가  0.767493                                    최고가  0.832185                                    최고가  0.814126                                     종가  0.948256
2                                      종가  0.747660                                     종가  0.820868                                     종가  0.800776                                    최고가  0.947936
3                                     최저가  0.712841                               자기주식수(주)  0.813923                                    최저가  0.777085                                    최저가  0.944148
4                                    거래대금  0.686572                                    최저가  0.792540                                   거래대금  0.662196                             합계_기말인원(명)  0.833872
5                                     거래량  0.598758                            기간제_기말인원(명)  0.480034                                    거래량  0.493290                              합계_평균근속연수  0.788733
6                                   분기수익률  0.371295                                   거래대금  0.441876                                수익률상승하락  0.394310                            기간제_기말인원(명)  0.740025
7                          기간제_기말인원(여)(명)  0.348528                                  분기수익률  0.407930                                  분기수익률  0.383191                         기간제_기말인원(남)(명)  0.720481
8                             기간제_기말인원(명)  0.308102                              합계_평균근속연수  0.407035                     정규+무기계약_기말인원(남)(명)  0.380587                     정규+무기계약_기말인원(남)(명)  0.697375
9                              합계_기말인원(명)  0.283486                         기간제_기말인원(남)(명)  0.386057                        정규+무기계약_기말인원(명)  0.362591                           합계_기말인원_남(명)  0.669612
10                           합계_기말인원_여(명)  0.249658                                수익률상승하락  0.348499                           합계_기말인원_남(명)  0.350820                               자기주식수(주)  0.610949
11                                수익률상승하락  0.247809                                    거래량  0.004576                             합계_기말인원(명)  0.306096                        정규+무기계약_기말인원(명)  0.605841
12                              합계_평균근속연수  0.244718                          발행할 주식의 총수(주) -0.021183                     정규+무기계약_기말인원(여)(명)  0.243699                     정규+무기계약_기말인원(여)(명)  0.577876
13                         기간제_기말인원(남)(명)  0.210775                     현재까지 발행한 주식의 총수(주) -0.021183                              합계_평균근속연수  0.234972                                   거래대금  0.559174
14                           합계_기말인원_남(명)  0.172866  발행주식의 총수 (현재 발행한 주식수 - 현재 감소한 주식수)(주) -0.021183                           합계_기말인원_여(명)  0.121447                         기간제_기말인원(여)(명)  0.534573
15            유통주식수 (발행주식의 총수 - 자기주식수)(주)  0.166742            유통주식수 (발행주식의 총수 - 자기주식수)(주) -0.105729                               자기주식수(주)  0.027599                     현재까지 발행한 주식의 총수(주)  0.532918
16  발행주식의 총수 (현재 발행한 주식수 - 현재 감소한 주식수)(주)  0.166742                        합계_1인평균년간급여(천원) -0.153865            유통주식수 (발행주식의 총수 - 자기주식수)(주) -0.027599  발행주식의 총수 (현재 발행한 주식수 - 현재 감소한 주식수)(주)  0.532918
17                     현재까지 발행한 주식의 총수(주)  0.166742                           합계_기말인원_남(명) -0.194049                        합계_1인평균년간급여(천원) -0.161544                           합계_기말인원_여(명)  0.515304
18                     정규+무기계약_기말인원(남)(명)  0.045651                             합계_기말인원(명) -0.208737                          합계_년간평균급여(천원) -0.176834            유통주식수 (발행주식의 총수 - 자기주식수)(주)  0.438922
19                          합계_년간평균급여(천원) -0.124945                          합계_년간평균급여(천원) -0.217264                         기간제_기말인원(남)(명) -0.440455                          합계_년간평균급여(천원)  0.432357
20                        합계_1인평균년간급여(천원) -0.174469                         기간제_기말인원(여)(명) -0.224625                         기간제_기말인원(여)(명) -0.598780                        합계_1인평균년간급여(천원)  0.361564
21                        정규+무기계약_기말인원(명) -0.210158                     정규+무기계약_기말인원(여)(명) -0.228041                            기간제_기말인원(명) -0.653123                                수익률상승하락  0.230213
22                     정규+무기계약_기말인원(여)(명) -0.592488                        정규+무기계약_기말인원(명) -0.250732                                  거래소코드       NaN                                  분기수익률  0.207892
23                                  거래소코드       NaN                     정규+무기계약_기말인원(남)(명) -0.253118                                 주식의 종류       NaN                          발행할 주식의 총수(주)  0.086210
24                                 주식의 종류       NaN                           합계_기말인원_여(명) -0.272744                          발행할 주식의 총수(주)       NaN                                    거래량 -0.373510
25                          발행할 주식의 총수(주)       NaN                                  거래소코드       NaN                     현재까지 발행한 주식의 총수(주)       NaN                                  거래소코드       NaN
26                     현재까지 감소한 주식의 총수(주)       NaN                                 주식의 종류       NaN                     현재까지 감소한 주식의 총수(주)       NaN                                 주식의 종류       NaN
27                                이익소각(주)       NaN                     현재까지 감소한 주식의 총수(주)       NaN                                이익소각(주)       NaN                     현재까지 감소한 주식의 총수(주)       NaN
28                               자기주식수(주)       NaN                                이익소각(주)       NaN  발행주식의 총수 (현재 발행한 주식수 - 현재 감소한 주식수)(주)       NaN                                이익소각(주)       NaN

In [14]:
list_corr = []
order = 20 # 기업별로 상위 30개 상관관계 변수 추출

for i in range(len(df_lg.index[:order])):
    list_corr.append(df_lg.index[:order][i])
    list_corr.append(df_sdi.index[:order][i])
    list_corr.append(df_ssem.index[:order][i])
    list_corr.append(df_hynix.index[:order][i])

variable = pd.Series(list_corr).value_counts()
variable = pd.DataFrame(variable).reset_index()
variable.columns = ['var_index', 'number']

In [15]:
var = []
for i in range(len(variable)):
    var.append(df_lg[df_lg.index == variable['var_index'][i]]['지표'].values[0])
var = pd.DataFrame(var)
var.columns = ['var']

In [16]:
corr = pd.concat([variable,var], axis = 1)
corr = corr[['var_index','var','number']]

In [17]:
corr = corr[corr['var'] != '3개월후종가'].reset_index(drop = True)
corr = corr[corr['var'] != '수익률상승하락'].reset_index(drop = True)
corr

    var_index                                    var  number
0          12                         기간제_기말인원(남)(명)       4
1          25                                   거래대금       4
2          23                                     종가       4
3          22                                    최저가       4
4          21                                    최고가       4
5          20                              합계_평균근속연수       4
6           5            유통주식수 (발행주식의 총수 - 자기주식수)(주)       4
7          18                          합계_년간평균급여(천원)       4
8          17                             합계_기말인원(명)       4
9          15                           합계_기말인원_남(명)       4
10          3                     현재까지 발행한 주식의 총수(주)       3
11          7  발행주식의 총수 (현재 발행한 주식수 - 현재 감소한 주식수)(주)       3
12          8                               자기주식수(주)       3
13          9                     정규+무기계약_기말인원(남)(명)       3
14         16                           합계_기말인원_여(명)       3
15         14                            기간제_기말인원(명)       3
16         27                                  분기수익률       3
17         24                                    거래량       3
18         11                        정규+무기계약_기말인원(명)       2
19         10                     정규+무기계약_기말인원(여)(명)       2
20         13                         기간제_기말인원(여)(명)       2
21         19                        합계_1인평균년간급여(천원)       2
22          2                          발행할 주식의 총수(주)       1

# 위 자료를 보고 변수 선정

In [18]:
deep_lg = lg[corr['var'][0:18]]
deep_sdi = sdi[corr['var'][0:18]]
deep_ssem = ssem[corr['var'][0:18]]
deep_hynix = hynix[corr['var'][0:18]]

deep_lg['수익률상승하락'] = lg['수익률상승하락']
deep_sdi['수익률상승하락'] = sdi['수익률상승하락']
deep_ssem['수익률상승하락'] = ssem['수익률상승하락']
deep_hynix['수익률상승하락'] = hynix['수익률상승하락']

# ------------ validation --------------

deep_samsungelectric = samsungelectric[corr['var'][0:18]]
deep_lgelectric = lgelectric[corr['var'][0:18]]
deep_sds = sds[corr['var'][0:18]]
deep_lgdisplay = lgdisplay[corr['var'][0:18]]

deep_samsungelectric['수익률상승하락'] = samsungelectric['수익률상승하락']
deep_lgelectric['수익률상승하락'] = lgelectric['수익률상승하락']
deep_sds['수익률상승하락'] = sds['수익률상승하락']
deep_lgdisplay['수익률상승하락'] = lgdisplay['수익률상승하락']

In [19]:
# 표준화

from sklearn.preprocessing import StandardScaler

scaler_lg = StandardScaler()
scale_lg = pd.DataFrame(scaler_lg.fit_transform(deep_lg.iloc[:,:-1]))

scaler_sdi = StandardScaler()
scale_sdi = pd.DataFrame(scaler_sdi.fit_transform(deep_sdi.iloc[:,:-1]))

scaler_ssem = StandardScaler()
scale_ssem = pd.DataFrame(scaler_ssem.fit_transform(deep_ssem.iloc[:,:-1]))

scaler_hynix = StandardScaler()
scale_hynix = pd.DataFrame(scaler_hynix.fit_transform(deep_hynix.iloc[:,:-1]))

# ------------ validation --------------

scaler_samsungelectric = StandardScaler()
scale_samsungelectric = pd.DataFrame(scaler_lg.fit_transform(deep_samsungelectric.iloc[:,:-1]))

scaler_lgelectric = StandardScaler()
scale_lgelectric = pd.DataFrame(scaler_sdi.fit_transform(deep_lgelectric.iloc[:,:-1]))

scaler_sds = StandardScaler()
scale_sds = pd.DataFrame(scaler_ssem.fit_transform(deep_sds.iloc[:,:-1]))

scaler_lgdisplay = StandardScaler()
scale_lgdisplay = pd.DataFrame(scaler_hynix.fit_transform(deep_lgdisplay.iloc[:,:-1]))


# 원래 값으로 변환
# scaler_lg.inverse_transform(scale_lg)

In [20]:
# 주가를 합치려고 만듬(마지막 열을 가져오면 됨)
deep_IT = pd.concat([deep_lg,deep_sdi,deep_ssem,deep_hynix], ignore_index=True)

# 표준화한 변수를 합치려고 만듬
scale_IT = pd.concat([scale_lg,scale_sdi,scale_ssem,scale_hynix], ignore_index=True)

# ------------ validation --------------

# 주가를 합치려고 만듬(마지막 열을 가져오면 됨)
deep_IT_validation = pd.concat([deep_samsungelectric,deep_lgelectric,deep_sds,deep_lgdisplay], ignore_index=True)

# 표준화한 변수를 합치려고 만듬
scale_IT_validation = pd.concat([scale_samsungelectric,scale_lgelectric,scale_sds,scale_lgdisplay], ignore_index=True)

# 샤비어함수 및 히든레이어 5개

# 및 Validation

In [ ]:
def xavier_init(n_inputs, n_outputs, uniform=True):
    if uniform:
        # 6 was used in the paper.
        init_range = tf.sqrt(6.0 / (n_inputs + n_outputs))
        return tf.random_uniform_initializer(-init_range, init_range)
    else:
        # 3 gives us approximately the same limints as above since this repicks
        # values greater than 2 standard deviations from the mean.
        stddev = tf.sqrt(3.0 / (n_inputs + n_outputs))
        return tf.truncated_normal_initializer(stddev=stddev)

In [24]:
# Review : Learning rate and Evaluation
import tensorflow as tf
import random
import matplotlib.pyplot as plt

tf.set_random_seed(777)  # reproducibility
tf.reset_default_graph()


x_data = scale_IT
y_data = deep_IT.iloc[:,[-1]]


# parameters
placeholder_num = len(x_data.columns)
learning_rate = 0.001




X = tf.placeholder(tf.float32, [None, placeholder_num])
Y = tf.placeholder(tf.float32, [None, 1])
keep_prob = tf.placeholder(tf.float32)


W1 = tf.get_variable("W1", shape=[placeholder_num, 32], initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([32]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L1 = tf.nn.dropout(L1, keep_prob=keep_prob)


W2 = tf.get_variable("W2", shape=[32, 64], initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([64]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L2 = tf.nn.dropout(L2, keep_prob=keep_prob)

W3 = tf.get_variable("W3", shape=[64, 64], initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([64]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L3 = tf.nn.dropout(L3, keep_prob=keep_prob)


W4 = tf.get_variable("W4", shape=[64, 32], initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([32]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
L4 = tf.nn.dropout(L4, keep_prob=keep_prob)


W5 = tf.get_variable("W5", shape=[32, 1], initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([1]))
L5 = tf.nn.relu(tf.matmul(L4, W5) + b5)

# hypothesis = tf.matmul(L4, W5) + b5

# define cost/loss & optimizer

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(L4,W5) + b5)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
# train = tf.train.AdamOptimizer(1e-4).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# <span style="color:red"> 가치주로 validation

In [22]:
# Launch graph



validation_number = 20
#init_state = lstm_cell.zero_state(128, tf.float32)

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(16201)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data.iloc[:-validation_number,:], Y: y_data.iloc[:-validation_number,:], keep_prob: 0.8})       
        if step % 200 == 0 or step < 10 :
            h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data.iloc[-validation_number:,:], Y: y_data.iloc[-validation_number:,:], keep_prob: 1.0})
            print("Step : {} \t Cost : {} \t Acc : {}".format(step, cost_val, a*100))

HBox(children=(IntProgress(value=0, max=16201), HTML(value='')))

Step : 0 	 Cost : 1.2501202821731567 	 Acc : 40.00000059604645
Step : 1 	 Cost : 1.2896232604980469 	 Acc : 40.00000059604645
Step : 2 	 Cost : 1.2155004739761353 	 Acc : 40.00000059604645
Step : 3 	 Cost : 1.309906005859375 	 Acc : 40.00000059604645
Step : 4 	 Cost : 1.2437527179718018 	 Acc : 40.00000059604645
Step : 5 	 Cost : 1.2023489475250244 	 Acc : 40.00000059604645
Step : 6 	 Cost : 1.2594443559646606 	 Acc : 40.00000059604645
Step : 7 	 Cost : 1.1187855005264282 	 Acc : 40.00000059604645
Step : 8 	 Cost : 1.1454201936721802 	 Acc : 40.00000059604645
Step : 9 	 Cost : 1.1034739017486572 	 Acc : 40.00000059604645
Step : 200 	 Cost : 0.8445152640342712 	 Acc : 60.00000238418579
Step : 400 	 Cost : 0.6844307780265808 	 Acc : 60.00000238418579
Step : 600 	 Cost : 0.6806612014770508 	 Acc : 60.00000238418579
Step : 800 	 Cost : 0.7010104060173035 	 Acc : 60.00000238418579
Step : 1000 	 Cost : 0.6028129458427429 	 Acc : 55.000001192092896
Step : 1200 	 Cost : 0.7100750803947449 	 Acc : 55.000001192092896
Step : 1400 	 Cost : 0.7070733308792114 	 Acc : 55.000001192092896
Step : 1600 	 Cost : 0.6439857482910156 	 Acc : 55.000001192092896
Step : 1800 	 Cost : 0.6950632333755493 	 Acc : 60.00000238418579
Step : 2000 	 Cost : 0.6081178188323975 	 Acc : 60.00000238418579
Step : 2200 	 Cost : 0.6332175731658936 	 Acc : 60.00000238418579
Step : 2400 	 Cost : 0.6726440787315369 	 Acc : 64.99999761581421
Step : 2600 	 Cost : 0.6434405446052551 	 Acc : 69.9999988079071
Step : 2800 	 Cost : 0.6353810429573059 	 Acc : 69.9999988079071
Step : 3000 	 Cost : 0.5626888871192932 	 Acc : 69.9999988079071
Step : 3200 	 Cost : 0.6001335382461548 	 Acc : 69.9999988079071
Step : 3400 	 Cost : 0.6481760740280151 	 Acc : 69.9999988079071
Step : 3600 	 Cost : 0.6326894760131836 	 Acc : 69.9999988079071
Step : 3800 	 Cost : 0.5657746195793152 	 Acc : 69.9999988079071
Step : 4000 	 Cost : 0.5967158079147339 	 Acc : 69.9999988079071
Step : 4200 	 Cost : 0.5213813185691833 	 Acc : 69.9999988079071
Step : 4400 	 Cost : 0.5268317461013794 	 Acc : 69.9999988079071
Step : 4600 	 Cost : 0.4748629927635193 	 Acc : 75.0
Step : 4800 	 Cost : 0.5156359672546387 	 Acc : 80.0000011920929
Step : 5000 	 Cost : 0.4693196415901184 	 Acc : 80.0000011920929
Step : 5200 	 Cost : 0.5592629313468933 	 Acc : 80.0000011920929
Step : 5400 	 Cost : 0.4864198863506317 	 Acc : 85.00000238418579
Step : 5600 	 Cost : 0.46037113666534424 	 Acc : 80.0000011920929
Step : 5800 	 Cost : 0.4207855463027954 	 Acc : 80.0000011920929
Step : 6000 	 Cost : 0.4288978576660156 	 Acc : 85.00000238418579
Step : 6200 	 Cost : 0.4439452886581421 	 Acc : 85.00000238418579
Step : 6400 	 Cost : 0.37626907229423523 	 Acc : 85.00000238418579
Step : 6600 	 Cost : 0.4687022864818573 	 Acc : 85.00000238418579
Step : 6800 	 Cost : 0.42500239610671997 	 Acc : 85.00000238418579
Step : 7000 	 Cost : 0.41400468349456787 	 Acc : 85.00000238418579
Step : 7200 	 Cost : 0.40770384669303894 	 Acc : 85.00000238418579
Step : 7400 	 Cost : 0.36613109707832336 	 Acc : 85.00000238418579
Step : 7600 	 Cost : 0.44179826974868774 	 Acc : 85.00000238418579
Step : 7800 	 Cost : 0.2858774960041046 	 Acc : 85.00000238418579
Step : 8000 	 Cost : 0.3646049499511719 	 Acc : 85.00000238418579
Step : 8200 	 Cost : 0.4157635271549225 	 Acc : 85.00000238418579
Step : 8400 	 Cost : 0.2817757725715637 	 Acc : 85.00000238418579
Step : 8600 	 Cost : 0.3144080936908722 	 Acc : 85.00000238418579
Step : 8800 	 Cost : 0.26411426067352295 	 Acc : 85.00000238418579
Step : 9000 	 Cost : 0.33709460496902466 	 Acc : 85.00000238418579
Step : 9200 	 Cost : 0.3106471300125122 	 Acc : 85.00000238418579
Step : 9400 	 Cost : 0.2901446521282196 	 Acc : 85.00000238418579
Step : 9600 	 Cost : 0.23473519086837769 	 Acc : 85.00000238418579
Step : 9800 	 Cost : 0.2031690925359726 	 Acc : 85.00000238418579
Step : 10000 	 Cost : 0.33124250173568726 	 Acc : 85.00000238418579
Step : 10200 	 Cost : 0.2569968104362488 	 Acc : 89.99999761581421
Step : 10400 	 Cost : 0.19502003490924835 	 Acc : 94.9999988079071
Step : 10600 	 Cost : nan 	 Acc : 40.00000059604645
Step : 10800 	 Cost : nan 	 Acc : 40.00000059604645
Step : 11000 	 Cost : nan 	 Acc : 40.00000059604645
Step : 11200 	 Cost : nan 	 Acc : 40.00000059604645
Step : 11400 	 Cost : nan 	 Acc : 40.00000059604645
Step : 11600 	 Cost : nan 	 Acc : 40.00000059604645
Step : 11800 	 Cost : nan 	 Acc : 40.00000059604645
Step : 12000 	 Cost : nan 	 Acc : 40.00000059604645
Step : 12200 	 Cost : nan 	 Acc : 40.00000059604645
Step : 12400 	 Cost : nan 	 Acc : 40.00000059604645
Step : 12600 	 Cost : nan 	 Acc : 40.00000059604645
Step : 12800 	 Cost : nan 	 Acc : 40.00000059604645
Step : 13000 	 Cost : nan 	 Acc : 40.00000059604645
Step : 13200 	 Cost : nan 	 Acc : 40.00000059604645
Step : 13400 	 Cost : nan 	 Acc : 40.00000059604645
Step : 13600 	 Cost : nan 	 Acc : 40.00000059604645
Step : 13800 	 Cost : nan 	 Acc : 40.00000059604645
Step : 14000 	 Cost : nan 	 Acc : 40.00000059604645
Step : 14200 	 Cost : nan 	 Acc : 40.00000059604645
Step : 14400 	 Cost : nan 	 Acc : 40.00000059604645
Step : 14600 	 Cost : nan 	 Acc : 40.00000059604645
Step : 14800 	 Cost : nan 	 Acc : 40.00000059604645
Step : 15000 	 Cost : nan 	 Acc : 40.00000059604645
Step : 15200 	 Cost : nan 	 Acc : 40.00000059604645
Step : 15400 	 Cost : nan 	 Acc : 40.00000059604645
Step : 15600 	 Cost : nan 	 Acc : 40.00000059604645
Step : 15800 	 Cost : nan 	 Acc : 40.00000059604645
Step : 16000 	 Cost : nan 	 Acc : 40.00000059604645
Step : 16200 	 Cost : nan 	 Acc : 40.00000059604645

# <span style="color:red"> 비 가치주로 validation

In [26]:
# Launch graph

validation_number = 20


# samsungelectric / lgelectric / sds / lgdisplay

# x_val_data = scale_lgdisplay
# y_val_data = deep_lgdisplay.iloc[:,[-1]]

x_val_data = scale_IT_validation
y_val_data = deep_IT_validation.iloc[:,[-1]]

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(12001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data.iloc[:-validation_number,:], Y: y_data.iloc[:-validation_number,:], keep_prob: 0.8})       
        if step % 200 == 0 or step < 10 :
            h, c, a = sess.run([hypothesis, predicted, accuracy],
                               feed_dict={X: x_val_data.iloc[:,:], Y: y_val_data.iloc[:,:], keep_prob: 1.0})
            print("Step : {} \t Cost : {} \t Acc : {}".format(step, cost_val, a*100))    

    # Accuracy report

HBox(children=(IntProgress(value=0, max=12001), HTML(value='')))

Step : 0 	 Cost : 0.8974726796150208 	 Acc : 46.296295523643494
Step : 1 	 Cost : 0.8911679983139038 	 Acc : 46.296295523643494
Step : 2 	 Cost : 0.9859977960586548 	 Acc : 46.296295523643494
Step : 3 	 Cost : 0.9993915557861328 	 Acc : 46.296295523643494
Step : 4 	 Cost : 1.0078418254852295 	 Acc : 46.296295523643494
Step : 5 	 Cost : 0.9858030080795288 	 Acc : 46.296295523643494
Step : 6 	 Cost : 0.9022290110588074 	 Acc : 46.296295523643494
Step : 7 	 Cost : 0.8843674063682556 	 Acc : 46.296295523643494
Step : 8 	 Cost : 0.8882926106452942 	 Acc : 46.296295523643494
Step : 9 	 Cost : 0.9443895816802979 	 Acc : 46.296295523643494
Step : 200 	 Cost : 0.757990837097168 	 Acc : 53.70370149612427
Step : 400 	 Cost : 0.7768641114234924 	 Acc : 53.70370149612427
Step : 600 	 Cost : 0.7053073048591614 	 Acc : 53.70370149612427
Step : 800 	 Cost : 0.7407109141349792 	 Acc : 55.55555820465088
Step : 1000 	 Cost : 0.735893964767456 	 Acc : 58.33333134651184
Step : 1200 	 Cost : 0.6434566974639893 	 Acc : 61.11111044883728
Step : 1400 	 Cost : 0.6831648349761963 	 Acc : 62.962961196899414
Step : 1600 	 Cost : 0.6796996593475342 	 Acc : 66.66666865348816
Step : 1800 	 Cost : 0.654502272605896 	 Acc : 69.44444179534912
Step : 2000 	 Cost : 0.6132560968399048 	 Acc : 71.29629850387573
Step : 2200 	 Cost : 0.6693639159202576 	 Acc : 74.0740716457367
Step : 2400 	 Cost : 0.6548945903778076 	 Acc : 74.0740716457367
Step : 2600 	 Cost : 0.6737035512924194 	 Acc : 74.0740716457367
Step : 2800 	 Cost : 0.6538316011428833 	 Acc : 75.0
Step : 3000 	 Cost : 0.6441782712936401 	 Acc : 77.77777910232544
Step : 3200 	 Cost : 0.6389329433441162 	 Acc : 78.70370149612427
Step : 3400 	 Cost : 0.6186673045158386 	 Acc : 79.62962985038757
Step : 3600 	 Cost : 0.5931235551834106 	 Acc : 78.70370149612427
Step : 3800 	 Cost : 0.5951846241950989 	 Acc : 80.55555820465088
Step : 4000 	 Cost : 0.6315845847129822 	 Acc : 79.62962985038757
Step : 4200 	 Cost : 0.612116277217865 	 Acc : 79.62962985038757
Step : 4400 	 Cost : 0.6098467707633972 	 Acc : 80.55555820465088
Step : 4600 	 Cost : 0.6195095777511597 	 Acc : 81.4814805984497
Step : 4800 	 Cost : 0.6156163811683655 	 Acc : 81.4814805984497
Step : 5000 	 Cost : 0.5561478734016418 	 Acc : 81.4814805984497
Step : 5200 	 Cost : 0.6288092732429504 	 Acc : 81.4814805984497
Step : 5400 	 Cost : 0.5870203971862793 	 Acc : 82.40740895271301
Step : 5600 	 Cost : 0.5859701037406921 	 Acc : 82.40740895271301
Step : 5800 	 Cost : 0.5583282709121704 	 Acc : 82.40740895271301
Step : 6000 	 Cost : 0.5577878355979919 	 Acc : 83.33333134651184
Step : 6200 	 Cost : 0.534774661064148 	 Acc : 84.25925970077515
Step : 6400 	 Cost : 0.5327430963516235 	 Acc : 85.18518805503845
Step : 6600 	 Cost : 0.5271722078323364 	 Acc : 84.25925970077515
Step : 6800 	 Cost : 0.4728788733482361 	 Acc : 84.25925970077515
Step : 7000 	 Cost : 0.5202752351760864 	 Acc : 84.25925970077515
Step : 7200 	 Cost : 0.509763777256012 	 Acc : 84.25925970077515
Step : 7400 	 Cost : 0.508542001247406 	 Acc : 85.18518805503845
Step : 7600 	 Cost : 0.4728858768939972 	 Acc : 86.11111044883728
Step : 7800 	 Cost : 0.4248744249343872 	 Acc : 86.11111044883728
Step : 8000 	 Cost : 0.472988486289978 	 Acc : 86.11111044883728
Step : 8200 	 Cost : 0.5224818587303162 	 Acc : 87.03703880310059
Step : 8400 	 Cost : 0.4360981583595276 	 Acc : 87.03703880310059
Step : 8600 	 Cost : 0.4363117814064026 	 Acc : 88.88888955116272
Step : 8800 	 Cost : 0.4455425441265106 	 Acc : 88.88888955116272
Step : 9000 	 Cost : 0.5184940695762634 	 Acc : 88.88888955116272
Step : 9200 	 Cost : 0.33326590061187744 	 Acc : 88.88888955116272
Step : 9400 	 Cost : 0.40048015117645264 	 Acc : 88.88888955116272
Step : 9600 	 Cost : 0.44590017199516296 	 Acc : 88.88888955116272
Step : 9800 	 Cost : 0.3780295252799988 	 Acc : 88.88888955116272
Step : 10000 	 Cost : 0.38622596859931946 	 Acc : 88.88888955116272
Step : 10200 	 Cost : 0.3536002039909363 	 Acc : 89.81481194496155
Step : 10400 	 Cost : 0.36096376180648804 	 Acc : 89.81481194496155
Step : 10600 	 Cost : 0.32534223794937134 	 Acc : 89.81481194496155
Step : 10800 	 Cost : 0.32688841223716736 	 Acc : 90.74074029922485
Step : 11000 	 Cost : 0.35961437225341797 	 Acc : 90.74074029922485
Step : 11200 	 Cost : 0.27741512656211853 	 Acc : 91.66666865348816
Step : 11400 	 Cost : 0.2706807255744934 	 Acc : 93.5185194015503
Step : 11600 	 Cost : 0.30855804681777954 	 Acc : 94.44444179534912
Step : 11800 	 Cost : 0.31199443340301514 	 Acc : 93.5185194015503
Step : 12000 	 Cost : 0.35019075870513916 	 Acc : 94.44444179534912

In [27]:
print('모델 정확도: ', a * 100 , '%')

모델 정확도:  94.44444179534912 %

In [30]:
# pd.DataFrame(y_data.iloc[-validation_number:,:].values, c.ravel()).reset_index()
pd.DataFrame({'real':list(y_val_data.iloc[:,:].values.ravel()),'predict': list(c.ravel())})

     real  predict
0     1.0      1.0
1     0.0      0.0
2     0.0      0.0
3     1.0      1.0
4     1.0      1.0
5     0.0      0.0
6     1.0      1.0
7     1.0      1.0
8     1.0      0.0
9     0.0      0.0
10    0.0      0.0
11    1.0      1.0
12    0.0      0.0
13    1.0      1.0
14    0.0      0.0
15    1.0      1.0
16    1.0      1.0
17    0.0      0.0
18    0.0      0.0
19    1.0      1.0
20    0.0      0.0
21    1.0      1.0
22    1.0      1.0
23    1.0      1.0
24    1.0      1.0
25    1.0      1.0
26    1.0      0.0
27    1.0      0.0
28    0.0      0.0
29    0.0      0.0
30    0.0      1.0
31    0.0      0.0
32    0.0      0.0
33    0.0      0.0
34    1.0      1.0
35    1.0      1.0
36    0.0      0.0
37    1.0      1.0
38    1.0      1.0
39    1.0      1.0
40    0.0      0.0
41    0.0      0.0
42    0.0      0.0
43    0.0      0.0
44    1.0      1.0
45    0.0      0.0
46    0.0      0.0
47    0.0      0.0
48    0.0      0.0
49    0.0      0.0
50    1.0      1.0
51    1.0      1.0
52    0.0      0.0
53    0.0      0.0
54    0.0      0.0
55    1.0      1.0
56    1.0      1.0
57    1.0      1.0
58    1.0      1.0
59    1.0      1.0
60    0.0      0.0
61    0.0      0.0
62    0.0      0.0
63    1.0      1.0
64    0.0      0.0
65    0.0      0.0
66    0.0      0.0
67    0.0      0.0
68    0.0      1.0
69    0.0      0.0
70    1.0      1.0
71    1.0      1.0
72    0.0      0.0
73    1.0      1.0
74    1.0      1.0
75    0.0      0.0
76    1.0      1.0
77    0.0      0.0
78    0.0      0.0
79    0.0      0.0
80    1.0      1.0
81    1.0      1.0
82    0.0      0.0
83    1.0      1.0
84    1.0      1.0
85    0.0      0.0
86    0.0      0.0
87    0.0      0.0
88    0.0      0.0
89    1.0      1.0
90    1.0      1.0
91    1.0      1.0
92    0.0      0.0
93    0.0      0.0
94    0.0      0.0
95    0.0      0.0
96    1.0      1.0
97    1.0      1.0
98    0.0      0.0
99    1.0      1.0
100   1.0      0.0
101   0.0      0.0
102   1.0      1.0
103   0.0      0.0
104   0.0      0.0
105   0.0      0.0
106   0.0      0.0
107   1.0      1.0

In [ ]:
h # hypothesis